# Generated by Django 2.2.4 on 2019-08-17 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_auto_20190817_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meals',
            name='preperation_time',
        ),
    ]
