# Generated by Django 2.2.4 on 2019-08-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_meals_preparation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='preparation_time',
            field=models.IntegerField(),
        ),
    ]
